//  ReflectionCatalog.swift
//  Komo
//
//  Localized reflection cards for the Home insight pool.
//  English source strings are also the stable catalog keys.

import Foundation

enum ReflectionCatalog {
    static var staticPool: [Reflection] {
        [
            .init(type: .add,
                  observation: loc("your energy often dips after back-to-back meetings."),
                  suggestion: loc("take 5 minutes outside before your next call."),
                  actions: [.addToCalendar, .save, .next],
                  topics: [.meetings]),
            .init(type: .reflect,
                  observation: loc("you slept 7+ hours on five nights this week."),
                  suggestion: loc("your body seems to recover better when sleep is consistent."),
                  actions: [.writeNote, .save, .next],
                  topics: [.napSleep, .poorSleep]),
            .init(type: .remind,
                  observation: loc("afternoons feel foggy on days you eat a heavy lunch."),
                  suggestion: loc("try a lighter lunch before 1pm today."),
                  actions: [.remindMe, .save, .next],
                  topics: []),
            .init(type: .remind,
                  observation: loc("your screen time usually climbs after 9pm."),
                  suggestion: loc("dim your phone at 9 tonight and see how your sleep feels."),
                  actions: [.remindMe, .save, .next],
                  topics: [.scrolling, .poorSleep]),
            .init(type: .start,
                  observation: loc("you skipped your usual workout today."),
                  suggestion: loc("try a quick 10-minute reset instead."),
                  actions: [.startNow, .save, .next],
                  topics: [.workout]),
            .init(type: .start,
                  observation: loc("mornings go better when you begin with focus instead of scrolling."),
                  suggestion: loc("start a 10-minute focus session."),
                  actions: [.startNow, .remindMe, .next],
                  topics: [.scrolling]),
            .init(type: .start,
                  observation: loc("someone's been on your mind."),
                  suggestion: loc("send a quick text or call them now."),
                  actions: [.startNow, .done, .next],
                  topics: [.timeWithFriends]),
            .init(type: .add,
                  observation: loc("your calendar looks packed before lunch."),
                  suggestion: loc("block 10 minutes after your last morning meeting."),
                  actions: [.addToCalendar, .next],
                  topics: [.meetings, .intenseWork]),
            .init(type: .remind,
                  observation: loc("you tend to sit for long stretches on workdays."),
                  suggestion: loc("stand up for 3 minutes before your next session."),
                  actions: [.remindMe, .done, .next],
                  topics: [.intenseWork]),
            .init(type: .start,
                  observation: loc("your energy looks low right now."),
                  suggestion: loc("do a 2-minute reset: breathe, stretch, drink water."),
                  actions: [.startNow, .next],
                  topics: []),
            .init(type: .remind,
                  observation: loc("late workouts seem to push your bedtime later."),
                  suggestion: loc("try moving your workout earlier today."),
                  actions: [.remindMe, .save, .next],
                  topics: [.workout, .poorSleep]),
            .init(type: .reflect,
                  observation: loc("you moved more than usual yesterday."),
                  suggestion: loc("your energy looks steadier after active days."),
                  actions: [.save, .writeNote, .next],
                  topics: [.workout, .walking]),
            .init(type: .start,
                  observation: loc("your focus usually improves after a short walk."),
                  suggestion: loc("take a 7-minute walk without your phone."),
                  actions: [.startNow, .done, .next],
                  topics: [.walking]),
            .init(type: .remind,
                  observation: loc("your evening energy crashes after long screen sessions."),
                  suggestion: loc("take a screen break before dinner."),
                  actions: [.remindMe, .next],
                  topics: [.scrolling]),
            .init(type: .add,
                  observation: loc("you have a heavy meeting block today."),
                  suggestion: loc("protect a recovery gap after it."),
                  actions: [.addToCalendar, .next],
                  topics: [.meetings]),
            .init(type: .start,
                  observation: loc("you look mentally loaded today."),
                  suggestion: loc("clear one small task in 10 minutes."),
                  actions: [.startNow, .next],
                  topics: [.intenseWork]),
            .init(type: .reflect,
                  observation: loc("quiet time seems to help you recharge."),
                  suggestion: loc("notice how you feel after 5 minutes without input."),
                  actions: [.writeNote, .save, .next],
                  topics: [.quietTime]),
            .init(type: .remind,
                  observation: loc("your sleep tends to suffer after late scrolling."),
                  suggestion: loc("start wind down mode at 9:30 tonight."),
                  actions: [.remindMe, .next],
                  topics: [.scrolling, .poorSleep]),
            .init(type: .start,
                  observation: loc("your body has been still for a while."),
                  suggestion: loc("move for 5 minutes. nothing heroic."),
                  actions: [.startNow, .done, .next],
                  topics: [.walking, .workout]),
            .init(type: .reflect,
                  observation: loc("your best energy window is usually in the morning."),
                  suggestion: loc("protect that window for deep work when you can."),
                  actions: [.save, .addToCalendar, .next],
                  topics: [.intenseWork]),
            .init(type: .remind,
                  observation: loc("your afternoon dips often follow low-movement mornings."),
                  suggestion: loc("take a short walk before lunch."),
                  actions: [.remindMe, .next],
                  topics: [.walking]),
            .init(type: .start,
                  observation: loc("you seem close to an energy crash."),
                  suggestion: loc("pause for 3 minutes before pushing through."),
                  actions: [.startNow, .next],
                  topics: []),
            .init(type: .reflect,
                  observation: loc("social time seems to recharge you on some days."),
                  suggestion: loc("notice who gives you energy, not just attention."),
                  actions: [.writeNote, .save, .next],
                  topics: [.timeWithFriends, .socialPlans]),
            .init(type: .remind,
                  observation: loc("your focus drops when meetings run back-to-back."),
                  suggestion: loc("leave 5 minutes between calls when possible."),
                  actions: [.addToCalendar, .save, .next],
                  topics: [.meetings]),
            .init(type: .start,
                  observation: loc("you have a small window right now."),
                  suggestion: loc("use it to reset, not scroll."),
                  actions: [.startNow, .next],
                  topics: [.scrolling]),
        ]
    }

    private static func loc(_ key: String.LocalizationValue) -> String {
        String(localized: key)
    }
}
